using System.Collections.Generic;
using UnityEngine;

/// <summary>캐릭터 풀을 보관하고, GachaRules를 이용해 뽑기를 수행</summary>
public class GachaSystem : MonoBehaviour
{
    [Header("캐릭터 풀")]
    public List<Character> characters;           // Inspector에서 확인 가능

    /* rarity별 캐시 */
    private readonly Dictionary<int, List<Character>> byRarity = new();

    /* ─────────────────────────────────────────── */
    void Awake()
    {
        /* 1) 풀 채우기 ─ 필요하다면 Inspector 대신 여기서 직접 입력 */
        characters = new List<Character>
        {   // 5성
            new Character { Name = "아만", Rarity = 5 },
            new Character { Name = "실리안", Rarity = 5 },
            new Character { Name = "국왕 실리안", Rarity = 5 },
            new Character { Name = "샨디", Rarity = 5 },
            new Character { Name = "진저웨일", Rarity = 5 },
            new Character { Name = "데런 아만", Rarity = 5 },
            new Character { Name = "웨이", Rarity = 5 },
            new Character { Name = "일리아칸", Rarity = 5 },
            new Character { Name = "카마인", Rarity = 5 },
            new Character { Name = "베아트리스", Rarity = 5 },
            new Character { Name = "아제나&이난나", Rarity = 5 },
            new Character { Name = "바훈투르", Rarity = 5 },
            new Character { Name = "가디언 루", Rarity = 5 },
            new Character { Name = "에스더 루테란", Rarity = 5 },
            new Character { Name = "에스더 시엔", Rarity = 5 },
            new Character { Name = "에스더 갈라투르", Rarity = 5 },
            new Character { Name = "니나브", Rarity = 5 },
            new Character { Name = "광기를 잃은 쿠크세이튼", Rarity = 5 },
            new Character { Name = "카단", Rarity = 5 },
            new Character { Name = "에버그레이스", Rarity = 5 },
            new Character { Name = "바르칸", Rarity = 5 },
            new Character { Name = "발탄", Rarity = 5 },
            new Character { Name = "쿠크세이튼", Rarity = 5 },
            new Character { Name = "비아키스", Rarity = 5 },
            new Character { Name = "아브렐슈드", Rarity = 5 },
            new Character { Name = "카멘", Rarity = 5 },
            new Character { Name = "부활하는 카제로스", Rarity = 5 },
            new Character { Name = "춤추는 쿠크세이튼", Rarity = 5 },
            new Character { Name = "교활한 카마인", Rarity = 5 },
            new Character { Name = "총사령관 실리안", Rarity = 5 },
            new Character { Name = "작전을 지휘하는 샨디", Rarity = 5 },
            new Character { Name = "선택한 아만", Rarity = 5 },
            new Character { Name = "심연의 방랑자", Rarity = 5 },
            new Character { Name = "각성한 진저웨일", Rarity = 5 },
            new Character { Name = "유적을 찾은 카단", Rarity = 5 },
            new Character { Name = "악몽의 아브렐슈드", Rarity = 5 },
            new Character { Name = "라제니스를 이끄는 니나브", Rarity = 5 },
            new Character { Name = "절망의 카멘", Rarity = 5 },
            new Character { Name = "바실리오", Rarity = 5 },
            new Character { Name = "구스토", Rarity = 5 },
            new Character { Name = "부패의 일리아칸", Rarity = 5 },
            new Character { Name = "욕망의 비아키스", Rarity = 5 },
            new Character { Name = "찢겨진 발탄", Rarity = 5 },
            new Character { Name = "피요르긴을 휘두르는 바훈투르", Rarity = 5 },
            new Character { Name = "전장을 지배하는 아제나", Rarity = 5 },
            new Character { Name = "도철을 다루는 웨이", Rarity = 5 },
            new Character { Name = "에키드나", Rarity = 5 },
            new Character { Name = "폭풍의 베히모스", Rarity = 5 },
            // 4성
            new Character { Name = "타나토스", Rarity = 4 },
            new Character { Name = "천둥날개", Rarity = 4 },
            new Character { Name = "슈헤리트", Rarity = 4 },
            new Character { Name = "알레그로", Rarity = 4 },
            new Character { Name = "마법사 로나운", Rarity = 4 },
            new Character { Name = "자간", Rarity = 4 },
            new Character { Name = "검은이빨", Rarity = 4 },
            new Character { Name = "모카모카", Rarity = 4 },
            new Character { Name = "하백", Rarity = 4 },
            new Character { Name = "반다", Rarity = 4 },
            new Character { Name = "바스티안", Rarity = 4 },
            new Character { Name = "사샤", Rarity = 4 },
            new Character { Name = "카인", Rarity = 4 },
            new Character { Name = "마리 파우렌츠", Rarity = 4 },
            new Character { Name = "진화의 군주 카인", Rarity = 4 },
            new Character { Name = "진 매드닉", Rarity = 4 },
            new Character { Name = "라하르트", Rarity = 4 },
            new Character { Name = "아나벨", Rarity = 4 },
            new Character { Name = "지그문트", Rarity = 4 },
            new Character { Name = "나크라세나", Rarity = 4 },
            new Character { Name = "레바노스", Rarity = 4 },
            new Character { Name = "베르투스", Rarity = 4 },
            new Character { Name = "크로마니움", Rarity = 4 },
            new Character { Name = "헬가이아", Rarity = 4 },
            new Character { Name = "빙결의 레기오로스", Rarity = 4 },
            new Character { Name = "어둠의 레기오로스", Rarity = 4 },
            new Character { Name = "에페르니아", Rarity = 4 },
            new Character { Name = "그노시스", Rarity = 4 },
            new Character { Name = "운다트", Rarity = 4 },
            new Character { Name = "실페리온", Rarity = 4 },
            new Character { Name = "케이사르", Rarity = 4 },
            new Character { Name = "벨크루제", Rarity = 4 },
            new Character { Name = "카이슈르", Rarity = 4 },
            new Character { Name = "사이카", Rarity = 4 },
            new Character { Name = "칼도르", Rarity = 4 },
            new Character { Name = "페데리코", Rarity = 4 },
            new Character { Name = "칼트말루스", Rarity = 4 },
            new Character { Name = "혼돈의 사이카", Rarity = 4 },
            new Character { Name = "아델", Rarity = 4 },
            new Character { Name = "에아달린", Rarity = 4 },
            new Character { Name = "엔비스카", Rarity = 4 },
            new Character { Name = "루메루스", Rarity = 4 },
            new Character { Name = "우르닐", Rarity = 4 },
            new Character { Name = "칼벤투스", Rarity = 4 },
            new Character { Name = "용암 크로마니움", Rarity = 4 },
            new Character { Name = "중갑 나크라세나", Rarity = 4 },
            new Character { Name = "홍염의 요호", Rarity = 4 },
            new Character { Name = "혹한의 헬가이아", Rarity = 4 },
            new Character { Name = "타이탈로스", Rarity = 4 },
            new Character { Name = "흑야의 요호", Rarity = 4 },
            new Character { Name = "벨가누스", Rarity = 4 },
            new Character { Name = "칼엘리고스", Rarity = 4 },
            new Character { Name = "아카테스", Rarity = 4 },
            new Character { Name = "이그렉시온", Rarity = 4 },
            new Character { Name = "미스틱", Rarity = 4 },
            new Character { Name = "카이슈테르", Rarity = 4 },
            new Character { Name = "엘버하스틱", Rarity = 4 },
            new Character { Name = "아르카디아", Rarity = 4 },
            new Character { Name = "피요르긴", Rarity = 4 },
            new Character { Name = "파르쿠나스", Rarity = 4 },
            new Character { Name = "나히니르", Rarity = 4 },
            new Character { Name = "신뢰의 아크 아스타", Rarity = 4 },
            new Character { Name = "창조의 아크 오르투스", Rarity = 4 },
            new Character { Name = "예지의 아크 아가톤", Rarity = 4 },
            new Character { Name = "희망의 아크 엘피스", Rarity = 4 },
            new Character { Name = "지혜의 아크 라디체", Rarity = 4 },
            new Character { Name = "헌신의 아크 카르타", Rarity = 4 },
            new Character { Name = "에르제베트", Rarity = 4 },
            new Character { Name = "크리스틴", Rarity = 4 },
            new Character { Name = "칼바서스", Rarity = 4 },
            new Character { Name = "니아", Rarity = 4 },
            new Character { Name = "샤나", Rarity = 4 },
            new Character { Name = "알비온", Rarity = 4 },
            new Character { Name = "아르고스", Rarity = 4 },
            new Character { Name = "데스칼루다", Rarity = 4 },
            new Character { Name = "쿤겔라니움", Rarity = 4 },
            new Character { Name = "하누마탄", Rarity = 4 },
            new Character { Name = "뮨 히다카", Rarity = 4 },
            new Character { Name = "오스피어", Rarity = 4 },
            new Character { Name = "다르시", Rarity = 4 },
            new Character { Name = "라우리엘", Rarity = 4 },
            new Character { Name = "영원의 아크 카양겔", Rarity = 4 },
            new Character { Name = "소나벨", Rarity = 4 },
            new Character { Name = "가르가디스", Rarity = 4 },
            new Character { Name = "어린 아만", Rarity = 4 },
            new Character { Name = "세헤라데", Rarity = 4 },
            new Character { Name = "베히모스", Rarity = 4 },
            new Character { Name = "라자람", Rarity = 4 },
            new Character { Name = "라카이서스", Rarity = 4 },
            new Character { Name = "칼테이야", Rarity = 4 },
            new Character { Name = "파이어혼", Rarity = 4 },
            new Character { Name = "베스칼", Rarity = 4 },
            new Character { Name = "다르키엘", Rarity = 4 },
            new Character { Name = "검은 산의 포식자", Rarity = 4 },
            new Character { Name = "모르페", Rarity = 4 },
            new Character { Name = "조롱하는 쿠크", Rarity = 4 },
            new Character { Name = "비웃는 세이튼", Rarity = 4 },
            new Character { Name = "태초의 악몽", Rarity = 4 },
            new Character { Name = "아슈타로테", Rarity = 4 },
            new Character { Name = "금기를 걷는 자 발리나크", Rarity = 4 },
            new Character { Name = "칠흑의 숭배자 킬리네사", Rarity = 4 },
            new Character { Name = "비통의 지배자 마우르그", Rarity = 4 },
            new Character { Name = "렌", Rarity = 4 },
            new Character { Name = "아게오로스", Rarity = 4 },
            new Character { Name = "스콜라키아", Rarity = 4 },
            // 3성
            new Character { Name = "바루투", Rarity = 3 },
            new Character { Name = "레온하트 네리아", Rarity = 3 },
            new Character { Name = "루드릭", Rarity = 3 },
            new Character { Name = "도굴단장 우고", Rarity = 3 },
            new Character { Name = "불칸", Rarity = 3 },
            new Character { Name = "역병 인도자", Rarity = 3 },
            new Character { Name = "하르잘", Rarity = 3 },
            new Character { Name = "소금거인", Rarity = 3 },
            new Character { Name = "천둥", Rarity = 3 },
            new Character { Name = "칼라도세", Rarity = 3 },
            new Character { Name = "미한", Rarity = 3 },
            new Character { Name = "릭투스", Rarity = 3 },
            new Character { Name = "하셀링크", Rarity = 3 },
            new Character { Name = "로블롬", Rarity = 3 },
            new Character { Name = "알리페르", Rarity = 3 },
            new Character { Name = "루테란 성 네리아", Rarity = 3 },
            new Character { Name = "윌리윌리", Rarity = 3 },
            new Character { Name = "세리아", Rarity = 3 },
            new Character { Name = "사교도 대제사장", Rarity = 3 },
            new Character { Name = "자히아", Rarity = 3 },
            new Character { Name = "리게아스", Rarity = 3 },
            new Character { Name = "하울로크", Rarity = 3 },
            new Character { Name = "칼스 모론토", Rarity = 3 },
            new Character { Name = "히바이크", Rarity = 3 },
            new Character { Name = "녹스", Rarity = 3 },
            new Character { Name = "세티노", Rarity = 3 },
            new Character { Name = "토토마", Rarity = 3 },
            new Character { Name = "하이비 집행관", Rarity = 3 },
            new Character { Name = "수호자 에오로", Rarity = 3 },
            new Character { Name = "붉은 남작 에디", Rarity = 3 },
            new Character { Name = "수호자 티르", Rarity = 3 },
            new Character { Name = "거신 카스피엘", Rarity = 3 },
            new Character { Name = "아크의 수호자 오셀", Rarity = 3 },
            new Character { Name = "파한", Rarity = 3 },
            new Character { Name = "만포", Rarity = 3 },
            new Character { Name = "미령", Rarity = 3 },
            new Character { Name = "원포", Rarity = 3 },
            new Character { Name = "길달", Rarity = 3 },
            new Character { Name = "절망의 레키엘", Rarity = 3 },
            new Character { Name = "역병군단 바르토", Rarity = 3 },
            new Character { Name = "혼재의 추오", Rarity = 3 },
            new Character { Name = "슈테른 네리아", Rarity = 3 },
            new Character { Name = "시그나투스", Rarity = 3 },
            new Character { Name = "에스", Rarity = 3 },
            new Character { Name = "제이", Rarity = 3 },
            new Character { Name = "안톤", Rarity = 3 },
            new Character { Name = "바에단", Rarity = 3 },
            new Character { Name = "타르실라", Rarity = 3 },
            new Character { Name = "루아브", Rarity = 3 },
            new Character { Name = "시안", Rarity = 3 },
            new Character { Name = "마네스", Rarity = 3 },
            new Character { Name = "기드온", Rarity = 3 },
            new Character { Name = "가룸", Rarity = 3 },
            new Character { Name = "페일린", Rarity = 3 },
            new Character { Name = "고르곤", Rarity = 3 },
            new Character { Name = "프록시마", Rarity = 3 },
            new Character { Name = "에라스모", Rarity = 3 },
            new Character { Name = "두키킹", Rarity = 3 },
            new Character { Name = "브리아레오스", Rarity = 3 },
            new Character { Name = "고르카그로스", Rarity = 3 },
            new Character { Name = "수신 아포라스", Rarity = 3 },
            new Character { Name = "실험체 타르마쿰", Rarity = 3 },
            new Character { Name = "솔 그랑데", Rarity = 3 },
            new Character { Name = "엘레노아", Rarity = 3 },
            new Character { Name = "아벤", Rarity = 3 },
            new Character { Name = "게르디아", Rarity = 3 },
            new Character { Name = "오렐다", Rarity = 3 },
            new Character { Name = "몽환의 퀸", Rarity = 3 },
            new Character { Name = "몽환의 킹", Rarity = 3 },
            new Character { Name = "위대한 성 네리아", Rarity = 3 },
            new Character { Name = "피에르", Rarity = 3 },
            new Character { Name = "나잔", Rarity = 3 },
            new Character { Name = "키즈라", Rarity = 3 },
            new Character { Name = "에이케르", Rarity = 3 },
            new Character { Name = "나베르", Rarity = 3 },
            new Character { Name = "비올레", Rarity = 3 },
            new Character { Name = "굴딩", Rarity = 3 },
            new Character { Name = "변절자 제페토", Rarity = 3 },
            new Character { Name = "아드모스", Rarity = 3 },
            new Character { Name = "아이히만 박사", Rarity = 3 },
            new Character { Name = "패자의 검", Rarity = 3 },
            new Character { Name = "진멸의 창", Rarity = 3 },
            new Character { Name = "갈기파도 항구 네리아", Rarity = 3 },
            new Character { Name = "아비시나", Rarity = 3 },
            new Character { Name = "판다 푸푸", Rarity = 3 },
            new Character { Name = "샐리", Rarity = 3 },
            new Character { Name = "크누트", Rarity = 3 },
            new Character { Name = "아드린느", Rarity = 3 },
            new Character { Name = "자하라", Rarity = 3 },
            new Character { Name = "리루", Rarity = 3 },
            new Character { Name = "나기", Rarity = 3 },
            new Character { Name = "세토", Rarity = 3 },
            new Character { Name = "키케라", Rarity = 3 },
            new Character { Name = "스텔라", Rarity = 3 },
            new Character { Name = "하이거", Rarity = 3 },
            new Character { Name = "루기네", Rarity = 3 },
            new Character { Name = "제레온", Rarity = 3 },
            new Character { Name = "베른 젠로드", Rarity = 3 },
            new Character { Name = "칸다리아 네리아", Rarity = 3 },
            new Character { Name = "신디", Rarity = 3 },
            new Character { Name = "아르노", Rarity = 3 },
            new Character { Name = "바스키아", Rarity = 3 },
            new Character { Name = "사일러스", Rarity = 3 },
            new Character { Name = "앙케", Rarity = 3 },
            new Character { Name = "피엘라", Rarity = 3 },
            new Character { Name = "빌헬름", Rarity = 3 },
            new Character { Name = "하눈", Rarity = 3 },
            new Character { Name = "마리나", Rarity = 3 },
            new Character { Name = "아자키엘", Rarity = 3 },
            new Character { Name = "벨루마테", Rarity = 3 },
            new Character { Name = "디오게네스", Rarity = 3 },
            new Character { Name = "다이나웨일", Rarity = 3 },
            new Character { Name = "클라우디아", Rarity = 3 },
            new Character { Name = "알폰스 베디체", Rarity = 3 },
            new Character { Name = "자크라", Rarity = 3 },
            new Character { Name = "안토니오 주교", Rarity = 3 },
            new Character { Name = "로잘린 베디체", Rarity = 3 },
            new Character { Name = "마리우", Rarity = 3 },
            new Character { Name = "아이작", Rarity = 3 },
            new Character { Name = "마레가", Rarity = 3 },
            new Character { Name = "칼리나리 네리아", Rarity = 3 },
            new Character { Name = "통솔자 루가루", Rarity = 3 },
            new Character { Name = "파괴자 루카스", Rarity = 3 },
            new Character { Name = "악몽의 게헤나", Rarity = 3 },
            new Character { Name = "악몽의 헬카서스", Rarity = 3 },
            new Character { Name = "세트", Rarity = 3 },
            new Character { Name = "타무트", Rarity = 3 }
        };

        /* 2) 희귀도별 캐싱 */
        BuildRarityCache();
    }
    /* ─────────────────────────────────────────── */

    void BuildRarityCache()
    {
        byRarity.Clear();
        foreach (var c in characters)
        {
            if (!byRarity.ContainsKey(c.Rarity))
                byRarity[c.Rarity] = new List<Character>();
            byRarity[c.Rarity].Add(c);
        }
    }

    /* 단일 뽑기 (마지막 확정용 guaranteeFourPlus) */
    public Character DrawSingle(bool guaranteeFourPlus = false)
    {
        int rarity = guaranteeFourPlus ? 4 : GachaRules.RollRarity();
        if (!byRarity.ContainsKey(rarity)) rarity = 3;   // 보호
        var pool = byRarity[rarity];
        return pool[Random.Range(0, pool.Count)];
    }

    /* 10 + 1 뽑기 */
    public List<Character> DrawTenPlusOne()
    {
        var list = new List<Character>();
        for (int i = 0; i < 10; i++) list.Add(DrawSingle());
        list.Add(DrawSingle(true)); // 11번째 4★ 이상 확정
        return list;
    }
}